// ==========================================
// РЕЕСТР СПОСОБНОСТЕЙ КАРТ(ABILITIES)
// ==========================================
// "База данных" всех возможных механик карт., у одной карты может быть несколько спообностей
// Используется для маппинга ID способности на реальную игровую логику в движке.
import { AbilityBehavior, AbilityDefinition, TargetRequirement } from "@/shared/types.ts";

export const DEFAULT_ABILITIES: AbilityDefinition[] = [
    // --- Battlecry / Кличи (Срабатывают при выходе на стол) ---
    { id:                    "HEAL_HERO",
        name:                "Исцеление",
        behavior:            AbilityBehavior.HEAL_HERO,
        targetRequirement:   TargetRequirement.ANY,
        descriptionTemplate: "Клич: Восстановление {value} здоровья герою",
    },
    { id:                    "DAMAGE_ENEMY_HERO",
        name:                "Огненный шар",
        behavior:            AbilityBehavior.DAMAGE_ENEMY_HERO,
        targetRequirement:   TargetRequirement.ENEMY,
        descriptionTemplate: "Клич: {value} урона герою врага",
    },
    { id:                    "BUFF_SELF",
        name:                "Усиление",
        behavior:            AbilityBehavior.BUFF_SELF,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Клич: +{value}/+{value} к себе",
    },
    { id:                    "DRAW_CARD",
        name:                "Интеллект",
        behavior:            AbilityBehavior.DRAW_CARD,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Клич: Взять {value} карт(у)",
    },
    { id:                    "GAIN_ARMOR",
        name:                "Броня",
        behavior:            AbilityBehavior.GAIN_ARMOR,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Клич: +{value} к броне",
    },
    { id:                    "DISCOVER",
        name:                "Раскопки",
        behavior:            AbilityBehavior.DISCOVER,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Клич: Выберите одну из 3 карт",
    },

    // --- Keywords / Ключевые слова (Постоянные эффекты) ---
    { id:                    "TAUNT",
        name:                "Провокация",
        behavior:            AbilityBehavior.TAUNT,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Провокация",
    },
    { id:                    "CHARGE",
        name:                "Рывок",
        behavior:            AbilityBehavior.CHARGE,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Рывок",
    },
    { id:                    "WINDFURY",
        name:                "Неистовство",
        behavior:            AbilityBehavior.WINDFURY,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Неистовство (2 атаки)",
    },
    { id:                    "DIVINE_SHIELD",
        name:                "Бож. щит",
        behavior:            AbilityBehavior.DIVINE_SHIELD,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Божественный щит",
    },
    { id:                    "INSTAKILL",
        name:                "Мгн. убийство",
        behavior:            AbilityBehavior.INSTAKILL,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Мгновенное убийство",
    },
    { id:                    "REFLECTION",
        name:                "Отражение",
        behavior:            AbilityBehavior.REFLECTION,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Отражает 50% урона",
    },
    { id:                    "LIFESTEAL",
        name:                "Вампиризм",
        behavior:            AbilityBehavior.LIFESTEAL,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Вампиризм",
    },

    // --- Spells / Заклинания ---
    { id:                    "SPELL_DAMAGE",
        name:                "Урон",
        behavior:            AbilityBehavior.SPELL_DAMAGE,
        targetRequirement:   TargetRequirement.ANY,
        descriptionTemplate: "Наносит {value} урона",
    },
    { id:                    "SPELL_HEAL",
        name:                "Лечение",
        behavior:            AbilityBehavior.SPELL_HEAL,
        targetRequirement:   TargetRequirement.ANY,
        descriptionTemplate: "Лечит на {value}",
    },
    { id:                    "SPELL_AOE_ENEMY",
        name:                "Волна",
        behavior:            AbilityBehavior.SPELL_AOE_ENEMY,
        targetRequirement:   TargetRequirement.ENEMY,
        descriptionTemplate: "Урон всем врагам: {value}",
    },
    { id:                    "SPELL_BUFF",
        name:                "Бафф",
        behavior:            AbilityBehavior.SPELL_BUFF,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Дает +{value}/+{value}",
    },
    { id:                    "POISON",
        name:                "Яд",
        behavior:            AbilityBehavior.POISON,
        targetRequirement:   TargetRequirement.FRIENDLY,
        descriptionTemplate: "Первая атака отравляет цель на 3 хода",
    },
];